id: A666C0772
title: A Synopsis of Guru Padmasambhava’s Life
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 22:36:40.975114
  last_modified_at: 2022-02-28 22:36:40.975118
