id: A666C0772
title: A Prayer to Tārā
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 22:36:40.972961
  last_modified_at: 2022-02-28 22:36:40.972973
